
insert into "products" (
  "title",
  "desc",
  "info",
  "price",
  "imageUrl"
) values (
  'Bridal Package',
  'SBS CAN DRESS YOU HEAD TO TOE FROM THE ENGAGEMENT PARTY ALL THE WAY TO THE HONEYMOON! LET''S MAKE SURE YOU ARE READY TO SLAY FOR THE BIG DAY!
',
'WEDDING, REHERSAL DINNER, WELCOME PARTY, BACHELORETTE, ENGAGEMENT PARTY, ENGAGEMENT PHOTOS, HONEYMOON',
300,
'/images/bridalpackagei.png'
), (
  'Black Tie & Party Package',
  'ARE YOU GOING TO A BLACK TIE WEDDING AND DON''T EVEN KNOW WHERE TO START? YOU KNOW WHEN THE INVITE SAYS “BLACK TIE OPTIONAL”, AND IT ACTUALLY MEANS "MANDATORY". PERHAPS A BACHELLORETTE PARTY WITH MULTIPLE ABSURDELY THEMED EVENTS? GRAB YOUR ESPRESSO MARTINI, THIS PACKAGE IS FOR YOU!',
'BACHELORETTE PARTY, BLACK TIE WEDDING, FORMAL EVENT, AWARD SHOWS, MILESTONE BIRTHDAY PARTY, GALA',
300,
'/images/blacktiei.png'
), (
  'Vacation Package',
  'ARE YOU GOING TO LAKE COMO AND LONDON WITH A MAN YOU JUST MET? DO YOU NEED OUTFITS THAT WILL TAKE YOU FROM SIGHTSEEING TO A SEXY DINNER? PERHAPS A TROPICAL VACAY AND NOT TRYING TO PACK 45 OUTFITS? DID YOU MEET A MAN ON BUMBLE AND HE''S NOW FLYING YOU TO GREECE?
', 'EUROTRIP, TROPICAL VACAY, WORK TRIP & CONFERENCE',
300,
'/images/vacationi.png'
);
